name: Release Drive

on:
  push:
    branches: ["teldrive"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Zip release
        run: cd dist; zip -r ../teldrive-ui.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1
          files: teldrive-ui.zip
          prerelease: true
